### ISSUE TITLE
Fails

### ISSUE THREAD

**Issue by kevinSuttle** [kadirahq/storybook-deployer#1]
No idea what the issue is. Does this create a git branch for you locally? Do you need one? Some error message would be helpful.

```
❯ npm run storybook:deploy

> @watson-iot/platform-ui-primitives@0.0.7 storybook:deploy /Users/kevinSuttle/Code/platform-ui-primitives
> storybook-to-ghpages

=> Building storybook
/Users/kevinSuttle/Code/platform-ui-primitives/node_modules/@kadira/storybook-deployer/src/utils.js:15
  throw new Error(message);
  ^

Error: Exec code(1) on executing: node ./node_modules/.bin/build-storybook -o .out
undefined
    at Object.exec (/Users/kevinSuttle/Code/platform-ui-primitives/node_modules/@kadira/storybook-deployer/src/utils.js:15:9)
    at Object.<anonymous> (/Users/kevinSuttle/Code/platform-ui-primitives/node_modules/@kadira/storybook-deployer/bin/storybook_to_ghpages:24:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)

npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/kevinSuttle/.nvm/versions/node/v6.2.2/bin/node" "/Users/kevinSuttle/.nvm/versions/node/v6.2.2/bin/npm" "run" "storybook:deploy"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! @watson-iot/platform-ui-primitives@0.0.7 storybook:deploy: `storybook-to-ghpages`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @watson-iot/platform-ui-primitives@0.0.7 storybook:deploy script 'storybook-to-ghpages'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @watson-iot/platform-ui-primitives package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     storybook-to-ghpages
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @watson-iot/platform-ui-primitives
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @watson-iot/platform-ui-primitives
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kevinSuttle/Code/platform-ui-primitives/npm-debug.log

```

**Comment by arunoda** [comment]
Weird. Are you trying to deploy into the public gh-pages?

**Comment by arunoda** [comment]
May be check your git project is commitable. No conflicts, etc.

**Comment by kevinSuttle** [comment]
No, into a GHE server.

**Comment by lorensr** [comment]
I'm getting an error on the same line, reproducible with https://github.com/lorensr/segmented-control

```
macbook:segmented-control me$  git:(upstream ⚡ master) 1A npm ls @kadira/storybook-deployer
segmented-control@0.0.1 /Users/me/gh/segmented-control
└── @kadira/storybook-deployer@1.0.0 
```

```
macbook:segmented-control me$  git:(upstream ⚡ master) nr deploy-storybook

> segmented-control@0.0.1 deploy-storybook /Users/me/gh/segmented-control
> storybook-to-ghpages

=> Building storybook
/Users/me/gh/segmented-control/node_modules/@kadira/storybook-deployer/src/utils.js:15
  throw new Error(message);
  ^

Error: Exec code(1) on executing: git commit -m "Deploy Storybook to GitHub Pages"
undefined
    at Object.exec (/Users/me/gh/segmented-control/node_modules/@kadira/storybook-deployer/src/utils.js:15:9)
    at Object.<anonymous> (/Users/me/gh/segmented-control/node_modules/@kadira/storybook-deployer/bin/storybook_to_ghpages:38:14)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
    at node.js:999:3

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/5.4.1_1/bin/node" "/usr/local/bin/npm" "run" "deploy-storybook"
npm ERR! node v5.4.1
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! segmented-control@0.0.1 deploy-storybook: `storybook-to-ghpages`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the segmented-control@0.0.1 deploy-storybook script 'storybook-to-ghpages'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the segmented-control package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     storybook-to-ghpages
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs segmented-control
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls segmented-control
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/me/gh/segmented-control/npm-debug.log
```

**Comment by arunoda** [comment]
@lorensr let me check this now.

**Comment by arunoda** [comment]
I just fixed this with a new version `v1.1.0`. Try to reopen or (asked me) if this is not yet fixed.

**Comment by lorensr** [comment]
http://lorensr.me/segmented-control/

works now, thanks arunoda! 😊

**Comment by gusdaud** [comment]
Hey @kevinSuttle be sure that storybook is located in `.storybook` folder otherwise it will fail.

@arunoda I think it should show a more helpful error message. Thanks

**Comment by kevinSuttle** [comment]
Thanks @gusdaud. @arunoda is it possible to run this as a webhook on the repo?

**Comment by arunoda** [comment]
@kevinSuttle Not sure. If you are using CI I think it's possible.
May be you need to make sure, CI can push to GitHub.

**Comment by shadiabuhilal** [comment]
I have faced the same issue, and I found the solution.
You need to create babel config file inside `.storybook` directory, to allow babel to build your project correctly.

Note: you can require the root babel config using `babel.config.js` file.

For more info please check https://storybook.js.org/docs/configurations/custom-babel-config/#docs-content
